---
abstract: 'CSV view class'
author:
  - 'Michael Brown <mbrown@fensystems.co.uk>'
build_requires:
  Catalyst: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Controller: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Test: 0
  CatalystX::Component::Traits: 0
  Config::General: 0
  DBD::SQLite: 0
  DBIx::Class: 0
  DBIx::Class::Schema: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Moose: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-CSV
no_index:
  directory:
    - inc
    - t
recommends:
  Text::CSV_XS: 0
requires:
  Catalyst::View: 0
  Text::CSV: 0
  URI: 0
  perl: 5.9.5
resources:
  license: http://dev.perl.org/licenses/
version: 1.1.2
