--- #YAML:1.0
name:                Catalyst-View-CSV
version:             0.01
abstract:            Comma separated values or Delimiter separated values for your data 
license:             ~
author:              
    - Travis Chase <gaudeon@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    Text::CSV:                     1.00
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
